name: Dragon CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dragon-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dragon script
        run: ./scripts.sh